added name as a maintainer since revert deleted it
jeffw16/unt-grade-distributions pull request #2
Opened 2019-11-14 23:55 UTC by JayNasty

Title says it all.

2019-11-15 06:25 UTC, JayNasty commented
Added google analytics visitor counter successfully across chrome and firefox. Tested fine locally for me.

2019-11-16 04:00 UTC, jeffw16 requested changes

2019-11-16 04:00 UTC, jeffw16 commented on index.html
> +                <p style="text-align: center;">&copy; 2018&ndash;2019 the UNT Grade Distributions Team: <a href="https://garrettgu.com">Garrett Gu</a>, <a href="https://jeffw.xyz">Jeffrey Wang</a>, <
should be mailto:jordanhamilton@my.unt.edu

2019-11-16 04:00 UTC, jeffw16 commented on index.js
> +    return result.subj + " " + result.num + "." + result.sect + "  |  " + result.desc + "  |  (" + result.prof + ")  |   " + result.term;
why?

2019-11-16 04:00 UTC, jeffw16 commented on styles.css
> +      .col-md-5 {
please do not override bootstrap styles

2019-11-16 04:00 UTC, jeffw16 commented on index.html
> +                <p style="text-align: center;">&copy; 2018&ndash;2019 the UNT Grade Distributions Team: <a href="https://garrettgu.com">Garrett Gu</a>, <a href="https://jeffw.xyz">Jeffrey Wang</a>, <
with quotes surrounding the value of the `href` attribute

2019-12-13 03:45 UTC, jeffw16 approved these changes
LGTM

2019-12-13 03:46 UTC, merged